# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FlagsGen < Formula
  desc "A Go code generator for creating command-line flag parsers from struct definitions"
  homepage "https://github.com/buji-code/flags-gen"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/buji-code/flags-gen/releases/download/v0.1.1/flags-gen_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "e49a58a1ffc63ea859c3220ff82593b68a66aef1f3733e484cdd87d432cee184"

      def install
        bin.install "flags-gen"
      end
    end
    on_arm do
      url "https://github.com/buji-code/flags-gen/releases/download/v0.1.1/flags-gen_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "b9b6cb19e94ba53c12c0040b51584abff7291bea8979e002ec5a2840d54e9218"

      def install
        bin.install "flags-gen"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/buji-code/flags-gen/releases/download/v0.1.1/flags-gen_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "bf9b0155b4f46255bed2fc9f2bae99ac68a281eb81c81a0ef020c6e3b1765cc7"

        def install
          bin.install "flags-gen"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/buji-code/flags-gen/releases/download/v0.1.1/flags-gen_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "9a54337e4315ef398238b4c9977b3c452370aa4db1605065407a6690cfceac87"

        def install
          bin.install "flags-gen"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Generate flag parsers from Go structs:
        flags-gen -i input.go -o output.go

      See example usage at: https://github.com/buji-code/flags-gen#usage
    EOS
  end

  test do
    system "#{bin}/flags-gen version"
    system "#{bin}/flags-gen --help"
  end
end
